### ISSUE TITLE
Issue with frontier patterns

### ISSUE THREAD

**Issue by technomancy** [luaj/luaj#3]
> %f[set], a frontier pattern; such item matches an empty string at
> any position such that the next character belongs to set and the
> previous character does not belong to set. The set set is
> interpreted as previously described. The beginning and the end of
> the subject are handled as if they were the character '\0'.

-- Lua 5.2 Reference Manual, §6.4.1

In the reference interpreter (Lua 5.3.4), the code belows prints a blank line and nil, indicating that the first pattern matched ('o' is not in [%.], but '.' is) and that the second one didn't.

In LuaJ 3.0.1, however, the code fails with

```
  org.luaj.vm2.LuaError: frontier-pattern-handling.lua:9 vm error: java.lang.ArrayIndexOutOfBoundsException: -1
  stack traceback:
    frontier-pattern-handling.lua:9: in main chunk
    [Java]: in ?
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at lua.processScript(Unknown Source)
    at lua.main(Unknown Source)
  Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at org.luaj.vm2.lib.StringLib$MatchState.match_class(Unknown Source)
    at org.luaj.vm2.lib.StringLib$MatchState.matchbracketclass(Unknown Source)
    at org.luaj.vm2.lib.StringLib$MatchState.match(Unknown Source)
    at org.luaj.vm2.lib.StringLib$MatchState.start_capture(Unknown Source)
    at org.luaj.vm2.lib.StringLib$MatchState.match(Unknown Source)
    at org.luaj.vm2.lib.StringLib.str_find_aux(Unknown Source)
    at org.luaj.vm2.lib.StringLib$match.invoke(Unknown Source)
```

```lua
print(string.match("foo.", "(%f[%.])"))
print(string.match("foo", "(%f[%.])"))
```

**Comment by headcr4sh** [comment]
Thanks for the bug report.

Unfortunately, this repo is just an in-official mirror of the original luaj repo which is hosted over at SourceForge (https://sourceforge.net/projects/luaj/). This repo was my humble attempt to migrate the sources from the old CVS archives whilst preserving all of the commit history.

I tried to contact Ian Farmer and James Roseborough (the original luaj authors) a bunch of times, because I wanted to hand over the ownership of the GitHub organization (luaj) and the project (luaj).
Unfortunately -- as of today -- I was not able to reach them... :-(

(Long story short: I am not a luaj maintainer/committer and I am not able to cut any new releases which might end up in Maven Central or elsewhere,... so please don't be disappointed if I won't be able to triage your issue, provide fixes or release a patched version of luaj)

**Comment by technomancy** [comment]
No problem; thanks for the explanation.

**Comment by jberkel** [comment]
@headcr4sh it's a shame this project is no longer officially maintained. maybe jitpack.io could be an option to provide jar files from this repository? I have some other patches I could contribute (mostly build-system related).

**Comment by headcr4sh** [comment]
@jberkel 
Well,... since neither Ian nor James have answered to my contact requests so far, it might be a viable alternative to keep this unofficial fork alive by just working on it nevertheless.

If you are interested in pushing the project forward (jitpack.io might indeed be an option, since no-one I know would be able to push artifacts under the org.luaj groupId to Maven central) I am willing to merge in any useful changes. The original history of the original authors is preserved and I don't think it would do any harm...

I will make sure that the README file gets adjusted to make it absolutely clear that this repo is a fork without any contributions / knowledge of the original authors so far, to make sure that no more false assumptions are being made.

**Comment by jberkel** [comment]
@headcr4sh cool, I'll revisit my patches and then submit a PR here.

**Comment by headcr4sh** [comment]
Ok. Thanks for the information. I'll try to convert these two commits once I find the time (if anyone else with cvs2git knowledge kann provide a PR I'd also gladly merge that one)

**Comment by jberkel** [comment]
I don't think you can update via cvs2git, so you might need to do a reimport. I don't remember which tool I used for the conversion, you can find the repo here, maybe it could be used as a base: https://gitlab.com/jberkel/luaj

**Comment by plamentotev** [comment]
I think I found where the issue is. here is a patch file:

```diff
--- StringLib.java      2018-03-03 23:06:25.584417500 +0200
+++ luaj-3.0.1/src/core/org/luaj/vm2/lib/StringLib.java 2018-03-03 23:06:53.158652400 +0200
@@ -1066,9 +1066,12 @@
                                                        error("Missing [ after %f in pattern");
                                                }
                                                int ep = classend( poffset );
-                                               int previous = ( soffset == 0 ) ? 0 : s.luaByte( soffset - 1 );
+                                               int previous = ( soffset == 0 ) ? '\0' : s.luaByte( soffset - 1 );
+                                               // The C version does not do this check
+                                               // because in C strings are '\0' terminated
+                                               int next = ( soffset == s.length() ) ? '\0' : s.luaByte( soffset );
                                                if ( matchbracketclass( previous, poffset, ep - 1 ) ||
-                                                        matchbracketclass( s.luaByte( soffset ), poffset, ep - 1 ) )
+                                                        !matchbracketclass( next, poffset, ep - 1 ) )
                                                        return -1;
                                                poffset = ep;
                                                continue;
```
I would create PR once #4 is resolved.

As for the commits. This could be easily fix once the source forge is back online. I've created new issue  to track this better #5

**Comment by plamentotev** [comment]
@Enyby to be honest I forgot the details about this issue. I may take a look at it again but not sure if I would have time soon. Feel free to use the patch and create PR if you want.
